/* ================================================================
   PRODUCT DATA
   Add, remove, or edit products in this array. The catalogue, filters,
   product details, stock labels, and recommendations update automatically.
   Images can be a local path such as "images/shoe.jpg" or an online URL.
   ================================================================ */
window.PRODUCTS = [
  {
    id: "wilson-nba-drv-pro",
    name: "Wilson NBA DRV Pro",
    category: "Basketballs",
    price: 1695,
    oldPrice: 1895,
    rating: 4.4,
    reviews: 231,
    stock: 41,
    badge: "",
    image: "https://nbastore.com.ph/cdn/shop/files/1_f948e26d-2ead-4681-80ca-73a7b2339850_2400x.png?v=1765945373",
    icon: "🏀",
    colors: ["Brown"],
    sizes: ["Size 7 (29.5\")"],
    description: 
      "Outdoor basketball inspired by the official NBA game ball, featuring durable performance cover and inflation retention lining.",
  },

  {
    id: "nike-lebron-22",
    name: "Nike LeBron 22",
    category: "Footwear",
    price: 11295,
    oldPrice: 11995,
    rating: 4.9,
    reviews: 324,
    stock: 12,
    badge: "",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtq6VJETU0ESrUV21KeD6B4Ks2U1lw0e-Ks4tVvvFBew&s=10",
    icon: "👟",
    colors: ["Black / Gold", "White / Crimson"],
    sizes: ["US 8", "US 9", "US 10", "US 11", "US 12"],
    description:
      "Premium basketball shoe featuring responsive Zoom Air cushioning, lightweight support, and superior traction built for explosive performance.",
  },

{
  id: "nike-dri-fit-jersey",
  name: "Nike Dri-FIT Basketball Jersey",
  category: "Apparel",
  price: 1695,
  oldPrice: 1895,
  rating: 4.8,
  reviews: 257,
  stock: 33,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_lj-ilZwOKorJ8mp3CG8FAb9nyHfN44iqEnaNz7H_1w&s=10",
  icon: "👕",
  colors: ["Black", "White", "Blue"],
  sizes: ["S", "M", "L", "XL", "XXL"],
  description:
    "Sleeveless basketball jersey made with moisture-wicking fabric to provide lightweight comfort throughout the game.",
},
 {
  id: "spalding-54-portable",
  name: "Spalding 54\" Portable Basketball Hoop",
  category: "Hoops",
  price: 32995,
  oldPrice: 35995,
  rating: 4.9,
  reviews: 187,
  stock: 5,
  badge: "",
  image: "https://i5.walmartimages.com/seo/Spalding-54-inch-Shatter-proof-Polycarbonate-Exacta-Height-Portable-Basketball-Hoop-System_c1432f78-daf5-4c75-9bc3-0e637efc62d9.69a4bc450c9b24b33a98ae5ba0fbb7a0.jpeg",
  icon: "⛹️",
  colors: ["Black / Clear"],
  sizes: ["54-inch Backboard"],
  description:
    "Premium portable basketball hoop featuring a 54-inch tempered glass backboard, height adjustment from 7.5 to 10 feet, and a wheeled base for easy movement.",
},

  //BASKETBALLS

  {
  id: "wilson-evolution",
  name: "Wilson Evolution Game Basketball",
  category: "Basketballs",
  price: 4595,
  oldPrice: 4995,
  rating: 4.9,
  reviews: 512,
  stock: 18,
  badge: "",
  image: "https://olympicvillageunited.com/cdn/shop/files/4_75f687b8-5651-458b-b5d8-f27d0294159f.jpg?v=1763089298&width=1500",
  icon: "🏀",
  colors: ["Orange"],
  sizes: ["Size 7 (29.5\")"],
  description:
    "Premium composite leather basketball designed for indoor courts, featuring excellent grip, moisture absorption, and consistent bounce.",
},


{
  id: "molten-bg4500",
  name: "Molten BG4500 FIBA Basketball",
  category: "Basketballs",
  price: 3999,
  oldPrice: 4399,
  rating: 4.8,
  reviews: 284,
  stock: 22,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQy_K6qbDCti8he0V19CpzkYZEpuTN1XUgUA68B3nJpQZ7uSDbXsNjYVwkc&s=10",
  icon: "🏀",
  colors: ["Orange / Ivory"],
  sizes: ["Size 7 (29.5\")"],
  description:
    "Official FIBA-approved premium composite leather basketball with enhanced grip texture and superior ball control for indoor competition.",
},

{
  id: "spalding-tf1000",
  name: "Spalding TF-1000 Legacy",
  category: "Basketballs",
  price: 4295,
  oldPrice: 4695,
  rating: 4.7,
  reviews: 193,
  stock: 15,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWO7sawKyzrs0fUhfdKsOhh340TF0K5lxMcJDdapXiPw6EF8oOLDdl51Ol&s=10",
  icon: "🏀",
  colors: ["Orange"],
  sizes: ["Size 7 (29.5\")"],
  description:
    "High-performance indoor basketball featuring microfiber composite cover for exceptional feel, grip, and durability.",
},


{
  id: "nike-elite-allcourt",
  name: "Nike Elite All Court 8P",
  category: "Basketballs",
  price: 2145,
  oldPrice: 2495,
  rating: 4.6,
  reviews: 168,
  stock: 27,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsuIiaGD7em8_dyzdwVR5IMuaAzAXQrOrISOWyCnJCRbFPT1sDtquDKt0&s=10",
  icon: "🏀",
  colors: ["Orange / Black"],
  sizes: ["Size 7 (29.5\")"],
  description:
    "Versatile all-court basketball with deep channels and textured rubber composite construction for indoor and outdoor play.",
},


{
  id: "adidas-all-court-3",
  name: "adidas All Court 3.0 Basketball",
  category: "Basketballs",
  price: 1799,
  oldPrice: 2099,
  rating: 4.5,
  reviews: 147,
  stock: 34,
  badge: "",
  image: "https://cdn11.bigcommerce.com/s-tn8o8k48s5/images/stencil/500x659/products/24896/70146/887791402363_40__07356.1695318132.jpg?c=1",
  icon: "🏀",
  colors: ["Orange / Black"],
  sizes: ["Size 7 (29.5\")"],
  description:
    "Durable all-surface basketball with a textured cover that provides reliable grip and long-lasting outdoor performance.",
},

{
  id: "molten-bg3800",
  name: "Molten BG3800 Basketball",
  category: "Basketballs",
  price: 2899,
  oldPrice: 3199,
  rating: 4.7,
  reviews: 176,
  stock: 19,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFx1vSccXtLLtvZHwZva3n_Cgi15HXUQK_aRsdSU7c_75q6RgwwopCZAMU&s=10",
  icon: "🏀",
  colors: ["Orange / Ivory"],
  sizes: ["Size 7 (29.5\")"],
  description:
    "Premium indoor-outdoor basketball with FIBA-inspired design, enhanced grip texture, and excellent durability for training.",
},


{
  id: "spalding-react-tf250",
  name: "Spalding React TF-250",
  category: "Basketballs",
  price: 1895,
  oldPrice: 2195,
  rating: 4.3,
  reviews: 119,
  stock: 38,
  badge: "",
  image: "https://olympicvillageunited.com/cdn/shop/files/3_4b8209e9-1283-472d-8762-79363507da4f.jpg?v=1764554699&width=1500",
  icon: "🏀",
  colors: ["Orange"],
  sizes: ["Size 7 (29.5\")"],
  description:
    "Reliable indoor-outdoor basketball featuring a tacky composite cover and responsive bounce for recreational games.",
},


{
  id: "nike-everyday-playground",
  name: "Nike Everyday Playground 8P",
  category: "Basketballs",
  price: 1495,
  oldPrice: 1695,
  rating: 4.5,
  reviews: 207,
  stock: 46,
  badge: "",
  image: "https://static.nike.com/a/images/t_web_pdp_936_v2/f_auto,u_9ddf04c7-2a9a-4d76-add1-d15af8f0263d,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/3d8497f5-3a3a-43ed-a30e-e4dad3ce5312/NK+EVERYDAY+PLAYGROUND+8P+DEFL.png",
  icon: "🏀",
  colors: ["Orange / Black"],
  sizes: ["Size 7 (29.5\")"],
  description:
    "Outdoor-focused basketball with durable rubber construction, deep channels, and textured grip for everyday street games.",
},

{
  id: "molten-bg2000",
  name: "Molten BG2000 Basketball",
  category: "Basketballs",
  price: 1299,
  oldPrice: 1499,
  rating: 4.2,
  reviews: 98,
  stock: 53,
  badge: "",
  image: "https://olympicvillageunited.com/cdn/shop/files/1_1915aea8-a790-4bda-ac2d-89d835d97483.jpg?v=1726194415&width=640",
  icon: "🏀",
  colors: ["Orange / Ivory"],
  sizes: ["Size 7 (29.5\")"],
  description:
    "Entry-level training basketball built with durable rubber material, offering dependable grip and bounce for beginners and casual players.",
},

// BASKETBALL SHOES

{
  id: "nike-kd-18",
  name: "Nike KD 18",
  category: "Footwear",
  price: 9995,
  oldPrice: 10695,
  rating: 4.8,
  reviews: 281,
  stock: 16,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4cE1jddkwYEEBaHF_AN80xC03A8Kt_Bqfi2yg9piexA&s ",
  icon: "👟",
  colors: ["Navy / Orange", "White / Blue"],
  sizes: ["US 7", "US 8", "US 9", "US 10", "US 11"],
  description:
    "Kevin Durant's latest signature basketball shoe with responsive cushioning, breathable mesh upper, and exceptional court feel.",
},

{
  id: "nike-gt-cut-3",
  name: "Nike G.T. Cut 3",
  category: "Footwear",
  price: 10395,
  oldPrice: 10995,
  rating: 4.8,
  reviews: 247,
  stock: 9,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqnDKeHpL0i388ZI1kzHbTO-eFIa8lZQR1tx4aR4eWTA&s=10",
  icon: "👟",
  colors: ["White / Volt", "Black / Red"],
  sizes: ["US 8", "US 9", "US 10", "US 11"],
  description:
    "Designed for quick guards, featuring ZoomX foam, multidirectional traction, and lightweight construction for maximum agility.",
},

{
  id: "adidas-harden-vol9",
  name: "adidas Harden Vol. 9",
  category: "Footwear",
  price: 9795,
  oldPrice: 10495,
  rating: 4.7,
  reviews: 218,
  stock: 20,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTvU90HF1C6TAQM3ZkiUz6AsBLNd8rDg-pr2zJzbQqEg&s=10",
  icon: "👟",
  colors: ["Black", "Pink / Black"],
  sizes: ["US 8", "US 9", "US 10", "US 11", "US 12"],
  description:
    "James Harden's signature shoe featuring Lightstrike cushioning and a durable rubber outsole for elite court performance.",
},

{
  id: "adidas-dame-9",
  name: "adidas Dame 9",
  category: "Footwear",
  price: 8295,
  oldPrice: 8895,
  rating: 4.6,
  reviews: 189,
  stock: 24,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwSosDtg12Mf_VnaIvsZSZQsjAfZET5DTaQ9TdINWF1Q&s=10",
  icon: "👟",
  colors: ["Black / Red", "Grey / Blue"],
  sizes: ["US 7", "US 8", "US 9", "US 10", "US 11"],
  description:
    "Damian Lillard's signature basketball shoe with lightweight cushioning and outstanding stability for quick cuts.",
},

{
  id: "anta-kai-1",
  name: "ANTA KAI 1",
  category: "Footwear",
  price: 7695,
  oldPrice: 8295,
  rating: 4.9,
  reviews: 356,
  stock: 14,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSUtKOsl6wl8v31DQ89EFN0rrFfWN5-6Dl1CQ1aQM3aw&s=10",
  icon: "👟",
  colors: ["Artist on Court", "White / Purple"],
  sizes: ["US 8", "US 9", "US 10", "US 11"],
  description:
    "Kyrie Irving's signature ANTA basketball shoe offering elite traction, responsive cushioning, and premium comfort.",
},

{
  id: "anta-shock-wave-6",
  name: "ANTA Shock Wave 6 Pro",
  category: "Footwear",
  price: 6995,
  oldPrice: 7495,
  rating: 4.7,
  reviews: 172,
  stock: 18,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfSH9g6ZnZbgGujwEAj2fanHVhkv9nVr7rBH4XbxdSiA&s",
  icon: "👟",
  colors: ["Black / Green", "White / Blue"],
  sizes: ["US 8", "US 9", "US 10", "US 11"],
  description:
    "Performance basketball shoe engineered with carbon plate support and aggressive traction for competitive play.",
},

{
  id: "li-ning-wow-11",
  name: "Li-Ning Way of Wade 11",
  category: "Footwear",
  price: 12495,
  oldPrice: 13295,
  rating: 4.9,
  reviews: 205,
  stock: 7,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTByBPxDflhQ7yNRcUPpukp_j2drAFdsKbTRZGIeXKAXg&s=10",
  icon: "👟",
  colors: ["White / Gold", "Black"],
  sizes: ["US 8", "US 9", "US 10", "US 11", "US 12"],
  description:
    "Premium signature basketball shoe featuring Boom cushioning, carbon fiber plate, and elite lockdown support.",
},

{
  id: "puma-all-pro-nitro",
  name: "PUMA All-Pro NITRO",
  category: "Footwear",
  price: 7495,
  oldPrice: 8095,
  rating: 4.6,
  reviews: 163,
  stock: 21,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2eyrfB8FVYMFwDuRrbgT2fGsS9Z--Tm3Hu_NFH4BCsQ&s=10",
  icon: "👟",
  colors: ["Orange / White", "Black / Lime"],
  sizes: ["US 8", "US 9", "US 10", "US 11"],
  description:
    "Lightweight basketball shoe equipped with NITRO foam cushioning for explosive responsiveness and all-game comfort.",
},

{
  id: "under-armour-curry-12",
  name: "Under Armour Curry 12",
  category: "Footwear",
  price: 9595,
  oldPrice: 10195,
  rating: 4.8,
  reviews: 294,
  stock: 11,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZsAWsMAjQCXDwhtrie2rIHSnO_xd33qq2zk2s3lN2tQ&s=10",
  icon: "👟",
  colors: ["White / Blue", "Black / Gold"],
  sizes: ["US 8", "US 9", "US 10", "US 11", "US 12"],
  description:
    "Stephen Curry's signature basketball shoe with UA Flow cushioning delivering incredible grip without a traditional rubber outsole.",
},

// Shoes (5)

{
  id: "nike-calm-slide",
  name: "Nike Calm Recovery Slide",
  category: "Footwear",
  price: 2895,
  oldPrice: 3195,
  rating: 4.8,
  reviews: 241,
  stock: 29,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-cylrQNlmgIYFGqy9IBuBGLkyrLlped4VT9eIvP_H3w&s=10",
  icon: "👟",
  colors: ["Black", "Bone"],
  sizes: ["US 7", "US 8", "US 9", "US 10", "US 11"],
  description:
    "Soft foam Shoes designed to reduce foot fatigue with plush cushioning and a lightweight one-piece construction.",
},

{
  id: "adidas-adilette-comfort",
  name: "adidas Adilette Comfort",
  category: "Footwear",
  price: 2395,
  oldPrice: 2695,
  rating: 4.7,
  reviews: 198,
  stock: 34,
  badge: "",
  image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjk3_7R32EcERz-udQm73qlq_N3Ynik8DWrewwxFx6Cw&s=10",
  icon: "👟",
  colors: ["Black / White", "Grey"],
  sizes: ["US 7", "US 8", "US 9", "US 10", "US 11"],
  description:
    "Classic cushioned slides featuring a contoured footbed for post-game comfort and everyday wear.",
},

{
  id: "anta-recovery-slide",
  name: "ANTA Recovery Slide",
  category: "Footwear",
  price: 1995,
  oldPrice: 2295,
  rating: 4.6,
  reviews: 142,
  stock: 42,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfDS-0fo_Btb6e8amvlpFEl2Qa1Q0yHPybNe5OEMERjg&s=10",
  icon: "👟",
  colors: ["Black", "Khaki"],
  sizes: ["US 7", "US 8", "US 9", "US 10"],
  description:
    "High-rebound EVA Shoes designed to provide excellent cushioning and support after intense workouts.",
},

{
  id: "ooahh-sport-slide",
  name: "OOFOS OOahh Sport Slide",
  category: "Footwear",
  price: 4295,
  oldPrice: 4695,
  rating: 4.9,
  reviews: 327,
  stock: 17,
  badge: "",
  image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6QJWD8ns5O2RxxvuqoZE8bfzpv4MA_lhXSUHFHx4Vig&s=10",
  icon: "👟",
  colors: ["Black", "Navy"],
  sizes: ["US 8", "US 9", "US 10", "US 11"],
  description:
    "Recovery footwear engineered with OOfoam technology to absorb impact and reduce stress on joints and feet.",
},

{
  id: "hoka-ora-slide-3",
  name: "HOKA Ora Recovery Slide 3",
  category: "Footwear",
  price: 3995,
  oldPrice: 4395,
  rating: 4.8,
  reviews: 216,
  stock: 25,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIxmM79JlbHXfo7b4fEcOzTFTS4gJjeVIM1vHLXVwe6w&s=10",
  icon: "👟",
  colors: ["Black", "Olive"],
  sizes: ["US 8", "US 9", "US 10", "US 11", "US 12"],
  description:
    "Comfort-focused Shoes with oversized cushioning and breathable ventilation channels for all-day relief.",
},

// BASKETBALL Shoes

{
  id: "nike-elite-crew",
  name: "Nike Elite Crew Basketball Shoes",
  category: "Footwear",
  price: 895,
  oldPrice: 995,
  rating: 4.9,
  reviews: 518,
  stock: 61,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR05UMxl4wtmKOFWTKFidHDLw3Jiphr-QouMCtOnIGIQ&s=10",
  icon: "👟",
  colors: ["Black", "White"],
  sizes: ["M", "L", "XL"],
  description:
    "Professional basketball Shoes with targeted cushioning, arch support, and sweat-wicking fabric for maximum comfort.",
},

{
  id: "adidas-creator-365",
  name: "adidas Creator 365 Basketball Shoes",
  category: "Footwear",
  price: 795,
  oldPrice: 895,
  rating: 4.7,
  reviews: 274,
  stock: 73,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBJCWQR-Q8f764SQlimpkKzdKZoGEcXopWNNp7s000hA&s=10",
  icon: "👟",
  colors: ["White", "Black"],
  sizes: ["M", "L"],
  description:
    "Crew-length basketball Shoes featuring moisture-wicking yarns and strategic cushioning for extended comfort on the court.",
},

{
  id: "under-armour-performance-crew",
  name: "Under Armour Performance Tech Crew Shoes",
  category: "Footwear",
  price: 695,
  oldPrice: 795,
  rating: 4.6,
  reviews: 193,
  stock: 84,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdHZ8uXOf0boQjU0D122W-Hk1Fi5nunQ4boxixQi6r7Q&s=10",
  icon: "👟",
  colors: ["Black", "White / Grey"],
  sizes: ["M", "L", "XL"],
  description:
    "Lightweight performance crew Shoes with dynamic arch support and breathable mesh panels designed for basketball players.",
},

// TRAINING EQUIPMENT (10)

{
  id: "agility-cone-set",
  name: "Pro Agility Cone Set (20 pcs)",
  category: "Training",
  price: 895,
  oldPrice: 1095,
  rating: 4.8,
  reviews: 162,
  stock: 31,
  badge: "",
  image: "https://m.media-amazon.com/images/I/71c7g3AmTcL._AC_UF1000,1000_QL80_.jpg",
  icon: "🔶",
  colors: ["Orange"],
  sizes: ["20 Pieces"],
  description:
    "Durable flexible training cones ideal for dribbling drills, agility exercises, speed work, and court positioning.",
},

{
  id: "weighted-jump-rope",
  name: "Performance Weighted Jump Rope",
  category: "Training",
  price: 1295,
  oldPrice: 1495,
  rating: 4.7,
  reviews: 143,
  stock: 24,
  badge: "",
  image: "https://assets.roguefitness.com/f_auto,q_auto,c_limit,w_1600,b_rgb:ffffff/catalog/Conditioning/Jump%20Ropes%20/Weighted%20Ropes/HEAVYROPE/HEAVYROPE-H_jkbidk.png",
  icon: "🚩",
  colors: ["Black / Red"],
  sizes: ["3 m"],
  description:
    "Adjustable weighted jump rope designed to improve footwork, endurance, coordination, and cardiovascular conditioning.",
},

{
  id: "defensive-mannequin",
  name: "Basketball Defensive Training Mannequin",
  category: "Training",
  price: 4495,
  oldPrice: 4995,
  rating: 4.9,
  reviews: 86,
  stock: 10,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRR4EdVmIxM4bIY1-3g97Ou3wrMjRUuR22n7Ct_02-aVw&s=10",
  icon: "🚩",
  colors: ["Yellow"],
  sizes: ["6 ft"],
  description:
    "Lightweight freestanding defensive mannequin for practicing crossovers, finishes, passing angles, and offensive moves.",
},

{
  id: "blocking-pad",
  name: "Heavy-Duty Contact Blocking Pad",
  category: "Training",
  price: 3595,
  oldPrice: 3995,
  rating: 4.8,
  reviews: 74,
  stock: 8,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWuFu85nRZbQRTDSftzPfkjcvzdrSgPAUqHE1SNntK2g&s=10",
  icon: "🚩",
  colors: ["Blue / Black"],
  sizes: ["Standard"],
  description:
    "High-density foam blocking pad built for contact finishing drills, defensive pressure training, and player development.",
},

{
  id: "speed-ladder",
  name: "Adjustable Speed Agility Ladder",
  category: "Training",
  price: 995,
  oldPrice: 1195,
  rating: 4.6,
  reviews: 211,
  stock: 37,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmpuaD_pq-f4qicEwNMFGpKTi4k0YHFT50CyI_75_kzw&s",
  icon: "🚩",
  colors: ["Yellow / Black"],
  sizes: ["6 m"],
  description:
    "Professional agility ladder for improving foot speed, balance, coordination, and quick directional changes.",
},

{
  id: "reaction-light-set",
  name: "LED Reaction Training Lights",
  category: "Training",
  price: 6595,
  oldPrice: 7295,
  rating: 4.9,
  reviews: 58,
  stock: 6,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_DbvNFn4DHJOc2MGAXsSgBHZYSmUbWWGgArgUYPufig&s=10 ",
  icon: "🚩",
  colors: ["Multicolor"],
  sizes: ["6 Lights"],
  description:
    "Wireless reaction lights that enhance reflexes, reaction time, defensive awareness, and decision-making during basketball drills.",
},

{
  id: "dribble-goggles",
  name: "Vision Restriction Dribble Goggles",
  category: "Training",
  price: 1195,
  oldPrice: 1395,
  rating: 4.5,
  reviews: 127,
  stock: 28,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhgChbPgg6KKivG2NGnv6kA0XYp9vT47kBKcMKnnKcaQ&s",
  icon: "🚩",
  colors: ["Black"],
  sizes: ["One Size"],
  description:
    "Training goggles that block downward vision to encourage better ball handling while keeping players' heads up.",
},

{
  id: "resistance-band-kit",
  name: "Athletic Resistance Band Kit",
  category: "Training",
  price: 1695,
  oldPrice: 1895,
  rating: 4.8,
  reviews: 189,
  stock: 33,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUIi2iJWROXdL2Gv1z08aca6XPT4bCfuwvfoanGjQqvw&s=10",
  icon: "🚩",
  colors: ["Black / Green"],
  sizes: ["5 Resistance Levels"],
  description:
    "Complete resistance band set for strength training, lateral movement drills, warm-ups, and injury prevention.",
},

{
  id: "rebound-net",
  name: "Portable Passing & Rebound Net",
  category: "Training",
  price: 5295,
  oldPrice: 5895,
  rating: 4.7,
  reviews: 69,
  stock: 11,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuQVNZ1_2ZNZMHQpQuWBb8x5d4-BCg72EV9qEDKrtFGQ&s",
  icon: "🚩",
  colors: ["Black"],
  sizes: ["40 x 40 in"],
  description:
    "Multi-angle rebound trainer that returns passes at different trajectories to improve passing, catching, and reaction speed.",
},

{
  id: "vertical-jump-trainer",
  name: "Vertical Jump Resistance Trainer",
  category: "Training",
  price: 2795,
  oldPrice: 3195,
  rating: 4.6,
  reviews: 104,
  stock: 19,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd1J0MiD00Sioz_ij9jfx9CBCIvOKio7FRaIv7_BuHoA&s",
  icon: "🚩",
  colors: ["Black / Orange"],
  sizes: ["Adjustable"],
  description:
    "Resistance-based jump trainer developed to increase lower-body explosiveness, jumping ability, and overall athletic performance.",
},

// ACCESSORIES (10)

{
  id: "nike-swoosh-headband",
  name: "Nike Swoosh Headband",
  category: "Accessories",
  price: 695,
  oldPrice: 795,
  rating: 4.8,
  reviews: 312,
  stock: 48,
  badge: "",
  image: "https://i5.walmartimages.com/seo/Nike-Swoosh-Headband-Black-White_460d8c5f-df3a-4d99-b58f-43135e5e7591_1.8b8e2d2544fd44ad8a250f9b0ab23fd1.jpeg",
  icon: "💪",
  colors: ["Black", "White", "Navy"],
  sizes: ["One Size"],
  description:
    "Soft, moisture-wicking headband designed to keep sweat away from your eyes during intense basketball games and workouts.",
},

{
  id: "under-armour-performance-headband",
  name: "Under Armour Performance Headband",
  category: "Accessories",
  price: 595,
  oldPrice: 695,
  rating: 4.7,
  reviews: 226,
  stock: 39,
  badge: "",
  image: "https://tse1.mm.bing.net/th/id/OIP.23gIcMyWjln1AjEvCq9SwAHaHa?r=0&pid=Api&h=220&P=0",
  icon: "💪",
  colors: ["Black", "Grey"],
  sizes: ["One Size"],
  description:
    "Stretch-fit performance headband featuring quick-dry fabric for lasting comfort on and off the court.",
},

{
  id: "nike-swoosh-wristbands",
  name: "Nike Swoosh Wristbands (Pair)",
  category: "Accessories",
  price: 495,
  oldPrice: 595,
  rating: 4.8,
  reviews: 281,
  stock: 57,
  badge: "",
  image: "https://static.nbastore.in/resized/1000X1000/677/nike-swoosh-1-pair-wristbands-black-black-672df7080fd8f.png?format=webp",
  icon: "💪",
  colors: ["Black", "White"],
  sizes: ["One Size"],
  description:
    "Highly absorbent cotton wristbands that help keep hands dry and improve grip throughout every game.",
},

{
  id: "adidas-wristband-set",
  name: "adidas Tennis & Basketball Wristbands",
  category: "Accessories",
  price: 445,
  oldPrice: 545,
  rating: 4.6,
  reviews: 194,
  stock: 62,
  badge: "",
  image: "https://worldofpadel.co.za/wp-content/uploads/2025/07/1_2824d655-f23f-4be0-b225-deffbc279a87-10.webp",
  icon: "💪",
  colors: ["White", "Black"],
  sizes: ["One Size"],
  description:
    "Comfortable stretch wristbands made with moisture-absorbing fabric for basketball training and competition.",
},

{
  id: "shock-doctor-mouthguard",
  name: "Shock Doctor Gel Max Mouthguard",
  category: "Accessories",
  price: 995,
  oldPrice: 1195,
  rating: 4.9,
  reviews: 167,
  stock: 26,
  badge: "",
  image: "https://cdn.shopify.com/s/files/1/0080/4719/8261/products/sd_6103_gelmax_blue-black_1000x1000_6aaba944-4ce6-47e4-869f-2ef1ea2779be_2000x.jpg?v=1608695237",
  icon: "💪",
  colors: ["Black", "Blue", "Red"],
  sizes: ["Adult"],
  description:
    "Heavy-duty mouthguard offering maximum protection while maintaining breathability and comfort during physical play.",
},

{
  id: "mcdavid-arm-sleeve",
  name: "McDavid Compression Arm Sleeve",
  category: "Accessories",
  price: 895,
  oldPrice: 995,
  rating: 4.8,
  reviews: 249,
  stock: 35,
  badge: "",
  image: "https://s7d2.scene7.com/is/image/academy/10345413?$pdp-gallery-ng$",
  icon: "💪",
  colors: ["Black", "White"],
  sizes: ["S", "M", "L", "XL"],
  description:
    "Compression arm sleeve that improves circulation, reduces muscle fatigue, and provides lightweight UV protection.",
},

{
  id: "nike-pro-leg-sleeve",
  name: "Nike Pro Basketball Leg Sleeve",
  category: "Accessories",
  price: 1195,
  oldPrice: 1345,
  rating: 4.7,
  reviews: 183,
  stock: 29,
  badge: "",
  image: "https://media-www.atmosphere.ca/product/div-01-hardgoods/dpt-12-team-sports/sdpt-20-basketball/333342935/nike-pro-strong-leg-sleeves-black-s-m--6fa39bd4-e54c-440b-8cb6-98a1f9ed0c70-jpgrendition.jpg",
  icon: "💪",
  colors: ["Black", "White"],
  sizes: ["M", "L", "XL"],
  description:
    "Compression leg sleeve offering muscle support, improved blood flow, and all-game comfort for basketball athletes.",
},

{
  id: "bauerfeind-knee-support",
  name: "Bauerfeind Sports Knee Support",
  category: "Accessories",
  price: 3295,
  oldPrice: 3595,
  rating: 4.9,
  reviews: 138,
  stock: 14,
  badge: "",
  image: "https://www.amazon.com/images/I/61ohq2nLg-L._AC_SL1500_._FMwebp_.jpg",
  icon: "💪",
  colors: ["Black"],
  sizes: ["S", "M", "L", "XL"],
  description:
    "Premium knee support engineered to stabilize the joint, reduce strain, and provide compression during high-impact movements.",
},

{
  id: "spalding-ball-pump",
  name: "Spalding Dual-Action Ball Pump",
  category: "Accessories",
  price: 545,
  oldPrice: 645,
  rating: 4.6,
  reviews: 154,
  stock: 43,
  badge: "",
  image: "https://forzasports.com/cdn/shop/files/spd8472dlpmp-chrnew01.jpg?crop=center&height=1200&v=1751206109&width=1200",
  icon: "💪",
  colors: ["Black / Orange"],
  sizes: ["Standard"],
  description:
    "Compact dual-action air pump with inflation needle for quickly inflating basketballs before practices and games.",
},

{
  id: "wilson-ball-carry-bag",
  name: "Wilson Mesh Basketball Carry Bag",
  category: "Accessories",
  price: 795,
  oldPrice: 895,
  rating: 4.7,
  reviews: 118,
  stock: 22,
  badge: "",
  image: "https://cdn11.bigcommerce.com/s-irb16l/images/stencil/2560w/products/838/16087/WTH1816__0_Wilson_BK_Ball_Mesh_Bag__28617.1724872604.png?c=2",
  icon: "💪",
  colors: ["Black"],
  sizes: ["Holds 6 Basketballs"],
  description:
    "Heavy-duty mesh equipment bag designed to carry multiple basketballs while providing ventilation and easy transport.",
},

// BASKETBALL BAGS

{
  id: "nike-elite-backpack",
  name: "Nike Elite Basketball Backpack",
  category: "Accessories",
  price: 3795,
  oldPrice: 4195,
  rating: 4.9,
  reviews: 418,
  stock: 21,
  badge: "",
  image: "https://www.tradeinn.com/f/13856/138562088/nike-elite-pro-basketball-backpack.jpg",
  icon: "💪",
  colors: ["Black", "Grey", "Navy"],
  sizes: ["32 L"],
  description:
    "Premium basketball backpack featuring a spacious main compartment, ventilated shoe pocket, padded laptop sleeve, and multiple accessory organizers.",
},

{
  id: "adidas-hoops-backpack",
  name: "adidas Hoops 3.0 Backpack",
  category: "Accessories",
  price: 2495,
  oldPrice: 2795,
  rating: 4.8,
  reviews: 287,
  stock: 34,
  badge: "",
  image: "https://www.supersports.co.th/cdn/shop/files/AD001AC561EETH-0.jpg?v=1739439554",
  icon: "💪",
  colors: ["Black", "Grey", "Royal Blue"],
  sizes: ["27 L"],
  description:
    "Versatile basketball backpack with padded shoulder straps, dual water bottle pockets, and a dedicated compartment for shoes or training gear.",
},

{
  id: "under-armour-undeniable-duffel",
  name: "Under Armour Undeniable 5.0 Duffel Bag",
  category: "Accessories",
  price: 2995,
  oldPrice: 3395,
  rating: 4.9,
  reviews: 352,
  stock: 18,
  badge: "",
  image: "https://www.recon-company.com/media/f8/9e/e2/1758527694/fb95d403aedd6d0e301ead4e01b6f064aa04aa5c.jpeg?ts=1758527694",
  icon: "💪",
  colors: ["Black", "Black / Red"],
  sizes: ["Medium (58 L)"],
  description:
    "Water-resistant gym duffel bag with a large main compartment, vented laundry pocket, and durable abrasion-resistant bottom panel.",
},

{
  id: "anta-training-duffel",
  name: "ANTA Training Gym Duffel",
  category: "Accessories",
  price: 2195,
  oldPrice: 2495,
  rating: 4.7,
  reviews: 169,
  stock: 26,
  badge: "",
  image: "https://anta.com/cdn/shop/files/3_64022ed3-2fad-4441-a0f5-45c8ea3ac3e3_1200x1200@2x.jpg?v=1739013543",
  icon: "💪",
  colors: ["Black", "Olive"],
  sizes: ["45 L"],
  description:
    "Lightweight gym bag designed for basketball players, featuring multiple storage compartments, an adjustable shoulder strap, and a ventilated shoe section.",
},

{
  id: "wilson-player-gear-bag",
  name: "Wilson Player Gear Basketball Bag",
  category: "Accessories",
  price: 2695,
  oldPrice: 2995,
  rating: 4.8,
  reviews: 196,
  stock: 15,
  badge: "",
  image: "https://cdn.apexwilson.com/cdn/2216/2025/09/08/WILSON-Evolution-Basketball-GearpackBlack-4140612-5723.jpg",
  icon: "💪",
  colors: ["Black / Orange"],
  sizes: ["50 L"],
  description:
    "Durable basketball gear bag capable of carrying shoes, apparel, accessories, and a basketball, with reinforced handles and heavy-duty zippers.",
},

// BASKETBALL HOOPS (10)



{
  id: "lifetime-52-adjustable",
  name: "Lifetime 52\" Adjustable Hoop",
  category: "Hoops",
  price: 26495,
  oldPrice: 28995,
  rating: 4.8,
  reviews: 231,
  stock: 8,
  badge: "",
  image: "https://www.lifetime.com/imagecache/kodachrome/product/main/ca1c7f7e-95a8-4832-bd82-c0e71fd80775.jpg?v=20201119220419",
  icon: "⛹️",
  colors: ["Black / Orange"],
  sizes: ["52-inch Backboard"],
  description:
    "Durable portable basketball system with a shatterproof backboard, Power Lift height adjustment, and weather-resistant construction.",
},

{
  id: "silverback-nxt54",
  name: "Silverback NXT 54 Basketball Hoop",
  category: "Hoops",
  price: 38995,
  oldPrice: 41995,
  rating: 4.9,
  reviews: 143,
  stock: 4,
  badge: "",
  image: "https://www.escaladesports.com/cdn/shop/files/Silverback_NXT_54_Portable_Basketball_Goal_-_Portable_B8401W_15_800x.jpg?v=1713816028",
  icon: "⛹️",
  colors: ["Black"],
  sizes: ["54-inch Backboard"],
  description:
    "Portable basketball hoop with Infinity Edge backboard technology, ultra-stable base, and quick height adjustment for serious players.",
},

{
  id: "goaliath-gs54c",
  name: "Goalrilla GS54C In-Ground Hoop",
  category: "Hoops",
  price: 74995,
  oldPrice: 79995,
  rating: 5.0,
  reviews: 92,
  stock: 3,
  badge: "",
  image: "https://www.swingsnthings.net/wp-content/uploads/2018/10/Goalrilla-GS54C-Basketball-Hoops-Cincinnati.jpg",
  icon: "⛹️",
  colors: ["Black / Clear"],
  sizes: ["54-inch Backboard"],
  description:
    "Professional-grade in-ground basketball hoop with tempered glass backboard, pro-style breakaway rim, and unmatched durability.",
},

{
  id: "lifetime-youth-hoop",
  name: "Lifetime Youth Adjustable Hoop",
  category: "Hoops",
  price: 8995,
  oldPrice: 9995,
  rating: 4.6,
  reviews: 168,
  stock: 17,
  badge: "",
  image: "https://www.lifetime.com/imagecache/kodachrome/product/main/be21b1d5-ec6c-40a4-98b5-8b2692fa94e9.jpg?v=20250718094810",
  icon: "⛹️",
  colors: ["Blue / Black"],
  sizes: ["32-inch Backboard"],
  description:
    "Perfect starter hoop for young players with adjustable height, impact-resistant backboard, and stable portable base.",
},

{
  id: "spalding-beast-60",
  name: "Spalding Beast 60\" Portable Hoop",
  category: "Hoops",
  price: 54995,
  oldPrice: 58995,
  rating: 4.9,
  reviews: 118,
  stock: 6,
  badge: "",
  image: "https://sportsmart.com.au/cdn/shop/files/80752_full.jpg?v=1691736715",
  icon: "⛹️",
  colors: ["Black / Clear"],
  sizes: ["60-inch Backboard"],
  description:
    "Elite portable basketball hoop with a massive tempered glass backboard, arena-style support frame, and smooth crank height adjustment.",
},

{
  id: "silverback-60-inground",
  name: "Silverback 60\" In-Ground Basketball Hoop",
  category: "Hoops",
  price: 68995,
  oldPrice: 72995,
  rating: 4.8,
  reviews: 101,
  stock: 2,
  badge: "",
  image: "https://cdn.shopify.com/s/files/1/0490/5710/4037/products/B5407F_Silverback_SBX_Ingroundhoop_800x.jpg?v=1652792514",
  icon: "⛹️",
  colors: ["Black"],
  sizes: ["60-inch Backboard"],
  description:
    "Heavy-duty in-ground hoop engineered for residential courts, featuring a tempered glass backboard and breakaway rim.",
},

{
  id: "goalsetter-all-american",
  name: "Goalsetter All-American Hoop",
  category: "Hoops",
  price: 82995,
  oldPrice: 87995,
  rating: 5.0,
  reviews: 74,
  stock: 2,
  badge: "",
  image: "https://rainbowoftheheartland.com/wp-content/uploads/2020/11/goalsetter-captain-thumb.jpg",
  icon: "⛹️",
  colors: ["Black / White"],
  sizes: ["54-inch Backboard"],
  description:
    "Premium American-made in-ground basketball system with precision height adjustment and professional rebounding performance.",
},

{
  id: "first-team-fury",
  name: "First Team Fury Adjustable Hoop",
  category: "Hoops",
  price: 46995,
  oldPrice: 49995,
  rating: 4.7,
  reviews: 89,
  stock: 5,
  badge: "",
  image: "https://tse2.mm.bing.net/th/id/OIP.Ozb-56-4pC7511fe5k4ahwHaJj?r=0&pid=Api&h=220&P=0",
  icon: "⛹️",
  colors: ["Black"],
  sizes: ["54-inch Backboard"],
  description:
    "Heavy-duty basketball hoop designed for home courts, featuring easy height adjustment and a powder-coated steel frame.",
},

{
  id: "macgregor-portable-hoop",
  name: "MacGregor Portable Basketball System",
  category: "Hoops",
  price: 18995,
  oldPrice: 20995,
  rating: 4.5,
  reviews: 137,
  stock: 12,
  badge: "",
  image: "https://i5.walmartimages.com/seo/Spalding-60-In-Acrylic-Screw-Jack-Portable-Basketball-Hoop-System_68e84151-aa78-4dbd-b3bf-215cb3ecd9bc.25d78a4a07732d8b54a06a54c5be9974.jpeg?odnHeight=424&odnWidth=424&odnBg=FFFFFF",
  icon: "⛹️",
  colors: ["Black / Red"],
  sizes: ["44-inch Backboard"],
  description:
    "Portable basketball hoop with adjustable height, durable polycarbonate backboard, and wheeled base for convenient storage and transport.",
},

// BASKETBALL SHORTS

{
  id: "nike-dri-fit-shorts",
  name: "Nike Dri-FIT Basketball Shorts",
  category: "Apparel",
  price: 1895,
  oldPrice: 2195,
  rating: 4.8,
  reviews: 274,
  stock: 36,
  badge: "",
  image: "https://static.nike.com/a/images/t_web_pdp_936_v2/f_auto/smsqtq9fsz7eyvfiqnp6/AS+M+NK+DF+11IN+SHORT.png",
  icon: "👕",
  colors: ["Black", "White", "Navy"],
  sizes: ["S", "M", "L", "XL", "XXL"],
  description:
    "Lightweight basketball shorts made with Dri-FIT technology to keep you cool, dry, and comfortable during games and training.",
},

{
  id: "adidas-own-the-game-shorts",
  name: "adidas Own The Game Shorts",
  category: "Apparel",
  price: 1695,
  oldPrice: 1895,
  rating: 4.7,
  reviews: 213,
  stock: 42,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHdGkMjXDGNP5HP5H717gbZ-9J8MrAG9UZkgBZfnyUhw&s",
  icon: "👕",
  colors: ["Black", "Grey", "Royal Blue"],
  sizes: ["S", "M", "L", "XL"],
  description:
    "Breathable basketball shorts featuring AEROREADY fabric and a relaxed fit for unrestricted movement on the court.",
},

{
  id: "under-armour-tech-shorts",
  name: "Under Armour Tech Mesh Shorts",
  category: "Apparel",
  price: 1795,
  oldPrice: 1995,
  rating: 4.8,
  reviews: 196,
  stock: 31,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaQRtW2b_aAX6EeQAezHSAXyccUexRjpOwewi75km56g&s=10",
  icon: "👕",
  colors: ["Black", "Red"],
  sizes: ["S", "M", "L", "XL", "XXL"],
  description:
    "Performance mesh basketball shorts with sweat-wicking technology and lightweight construction for all-day comfort.",
},

{
  id: "anta-court-shorts",
  name: "ANTA Court Performance Shorts",
  category: "Apparel",
  price: 1495,
  oldPrice: 1695,
  rating: 4.6,
  reviews: 148,
  stock: 39,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRR8gsC5-K_W8iXMLFFagI2LHBfv_RIgUhdCODzcysVcw&s",
  icon: "👕",
  colors: ["Black", "White", "Green"],
  sizes: ["M", "L", "XL"],
  description:
    "Quick-drying basketball shorts designed with stretch fabric for explosive movement and superior comfort.",
},

{
  id: "puma-hoops-shorts",
  name: "PUMA Hoops Team Shorts",
  category: "Apparel",
  price: 1595,
  oldPrice: 1795,
  rating: 4.7,
  reviews: 182,
  stock: 27,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV1siwU6yu03xY5GIvFNUkmY8OBsKErIIOqAQYGt04UQ&s=10",
  icon: "👕",
  colors: ["Black", "Orange"],
  sizes: ["S", "M", "L", "XL"],
  description:
    "Modern basketball shorts featuring breathable mesh panels and an athletic fit for practice or game day.",
},


// BASKETBALL JERSEYS / TOPS (5)



{
  id: "adidas-create-jersey",
  name: "adidas Creator Basketball Jersey",
  category: "Apparel",
  price: 1595,
  oldPrice: 1795,
  rating: 4.7,
  reviews: 201,
  stock: 37,
  badge: "",
  image: "https://epicsports.cachefly.net/variants/184120/134413/500/adidas-creator-365-mens-jersey.jpg     ",
  icon: "👕",
  colors: ["White", "Red", "Navy"],
  sizes: ["S", "M", "L", "XL"],
  description:
    "Classic basketball jersey featuring breathable AEROREADY fabric and a lightweight athletic cut.",
},

{
  id: "under-armour-baseline-jersey",
  name: "Under Armour Baseline Jersey",
  category: "Apparel",
  price: 1795,
  oldPrice: 1995,
  rating: 4.8,
  reviews: 164,
  stock: 29,
  badge: "",
  image: "https://sportlandamerican.com/58863-home_large/men-s-under-armour-baseline-reversible-tank-royal.webp",
  icon: "👕",
  colors: ["Black", "Royal Blue"],
  sizes: ["S", "M", "L", "XL", "XXL"],
  description:
    "High-performance basketball jersey with anti-odor technology and breathable mesh construction.",
},

{
  id: "anta-pro-jersey",
  name: "ANTA Pro Basketball Jersey",
  category: "Apparel",
  price: 1495,
  oldPrice: 1695,
  rating: 4.6,
  reviews: 139,
  stock: 41,
  badge: "",
  image: "https://img.myshopline.com/image/store/1768803635456/my-11134201-7rasc-m6do5clw698z50.jpg?w=800&h=800",
  icon: "👕",
  colors: ["Black", "White", "Purple"],
  sizes: ["M", "L", "XL"],
  description:
    "Athletic-fit sleeveless jersey offering lightweight comfort and excellent airflow during intense games.",
},

{
  id: "puma-hoops-jersey",
  name: "PUMA Hoops Performance Jersey",
  category: "Apparel",
  price: 1645,
  oldPrice: 1845,
  rating: 4.7,
  reviews: 177,
  stock: 35,
  badge: "",
  image: "https://cdn.sportshop.com/catalog/product/1500/1500/1/6/168436_1.jpg",
  icon: "👕",
  colors: ["Black", "Orange", "Grey"],
  sizes: ["S", "M", "L", "XL"],
  description:
    "Breathable basketball jersey built with lightweight polyester fabric for unrestricted movement and all-game comfort.",
},

// =======================
// COMPRESSION SHIRT (1)
// =======================

{
  id: "nike-pro-compression-top",
  name: "Nike Pro Compression Shirt",
  category: "Apparel",
  price: 1995,
  oldPrice: 2295,
  rating: 4.9,
  reviews: 326,
  stock: 24,
  badge: "",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVXVX7uKSB3IeD3fuvQkfQ7e981t6J52GrM5akyW7Xyf7uMGoAYQdNG9_w&s=10",
  icon: "👕",
  colors: ["Black", "White"],
  sizes: ["S", "M", "L", "XL", "XXL"],
  description:
    "Long-lasting compression training shirt featuring Dri-FIT technology that delivers muscle support, moisture management, and a close-performance fit under your basketball jersey.",
},


];
